//! 构建期内核插件自动发现（ADR-0036，参考 mistake-agent）：
//! 扫描 `src/plugin/*/mod.rs`（一层深），生成 `builtin_kernel_plugins.rs` 到 OUT_DIR，
//! 由 `src/plugin/mod.rs` 经 `include!` 引入。
//!
//! 规则（详见 docs/plugin-dev/kernel.md）：
//! - 目录即插件：一层子目录内存在 `mod.rs` 即收录；
//! - 禁用：目录根部存在 `disabled` 文件则整目录跳过（不编译、不注册）；
//! - 命名：目录名须匹配 `^[a-z][a-z0-9_]*$` 且非 Rust 关键字（目录名即模块名）；
//! - 无 `mod.rs` 的目录静默忽略；缺 `descriptor()` 由编译期报错兜住。

use std::fs;
use std::path::Path;

fn main() -> Result<(), String> {
    let out_dir = std::env::var("OUT_DIR").map_err(|e| format!("OUT_DIR 缺失：{e}"))?;
    generate_manifest("src/plugin", &out_dir)
}

fn generate_manifest(root: &str, out_dir: &str) -> Result<(), String> {
    // 目录内任何变化（新增/改名/删除/放 disabled 文件）都触发重扫。
    println!("cargo:rerun-if-changed={root}");

    let root_path = Path::new(root);
    let mut plugins: Vec<String> = Vec::new();
    if root_path.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(root_path)
            .map_err(|e| format!("读取插件目录 {root} 失败：{e}"))?
            .collect::<Result<_, _>>()
            .map_err(|e| format!("读取插件目录 {root} 失败：{e}"))?;
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let name = entry.file_name().to_string_lossy().into_owned();
            // 禁用：整目录跳过，连编译都不参与（WIP 半成品可安全放这里）。
            if path.join("disabled").is_file() {
                continue;
            }
            if !path.join("mod.rs").is_file() {
                continue;
            }
            validate_plugin_name(&name, &path)?;
            plugins.push(name);
        }
    }

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs（插件目录自动发现，勿手改；规则见 docs/plugin-dev/kernel.md）\n",
    );
    code.push_str("use crate::registry::KernelDescriptor;\n");
    for name in &plugins {
        // include! 内联后 `pub mod X;` 会按包含文件所在目录解析（src/），
        // 因此这里带绝对 #[path] 指向插件 mod.rs（构建期生成，路径按机器归一化）。
        let mod_path = Path::new(root)
            .join(name)
            .join("mod.rs")
            .canonicalize()
            .map_err(|e| format!("定位插件入口失败 {name}：{e}"))?
            .to_string_lossy()
            .replace('\\', "/");
        code.push_str(&format!("#[path = \"{mod_path}\"]\npub mod {name};\n"));
    }
    code.push('\n');
    code.push_str("/// 编译期内置内核插件清单（ADR-0036：构建期自动发现）。\n");
    code.push_str("pub fn builtin_kernel_plugins() -> Vec<KernelDescriptor> {\n");
    code.push_str("    vec![\n");
    for name in &plugins {
        code.push_str(&format!("        {name}::descriptor(),\n"));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");
    fs::write(Path::new(out_dir).join("builtin_kernel_plugins.rs"), code)
        .map_err(|e| format!("写生成清单失败：{e}"))
}

fn validate_plugin_name(name: &str, path: &Path) -> Result<(), String> {
    let mut bytes = name.bytes();
    let valid = match bytes.next() {
        Some(b) if b.is_ascii_lowercase() => {
            bytes.all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        }
        _ => false,
    };
    if !valid {
        return Err(format!(
            "插件目录名 `{name}` 不合法：须为小写蛇形（^[a-z][a-z0-9_]*$，目录名即模块名）：{}",
            path.display()
        ));
    }
    Ok(())
}
