//! 构建期内核插件自动发现（ADR-0036 改造，参考 mistake-agent；workspace 化后挂在二进制侧）：
//! 扫描 `crates/plugin-*/`（一层深，相对于本 crate 的上一级目录），读取各插件
//! crate 的包名，生成 `builtin_kernel_plugins.rs` 到 OUT_DIR，由 `src/builtin.rs`
//! 经 `include!` 引入。`sl-agent` 装配时逐条注册（Linus 模式：仅维护者能加插件 crate）。
//!
//! 规则（详见 docs/kernel-dev.md §4.4）：
//! - 目录即插件：`crates/plugin-<name>/` 且内含 Cargo.toml 即收录（一层深）；
//! - 包名约定：插件 crate 的 `[package] name` 须为 `sl-plugin-<name>`（合法 crate 名，
//!   连字符转下划线即 Rust 标识符）；目录名 `<name>` 须匹配 `^[a-z][a-z0-9_]*$`；
//! - 禁用：目录根部存在 `disabled` 文件则整目录跳过（不注册）；
//! - 装配零样板：新增插件只需建目录 + 根/二进制 Cargo.toml 各加一行依赖声明；
//!   本脚本自动生成注册清单，任何 Rust 装配代码都不用改。

use std::fs;
use std::path::Path;

fn main() -> Result<(), String> {
    let out_dir = std::env::var("OUT_DIR").map_err(|e| format!("OUT_DIR 缺失：{e}"))?;
    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").map_err(|e| format!("CARGO_MANIFEST_DIR 缺失：{e}"))?;
    // crates/sl-agent 的上一级是 crates/，插件约定 crates/plugin-*。
    let plugins_root = Path::new(&manifest_dir)
        .parent()
        .ok_or("无法定位 crates/ 目录")?;
    generate_manifest(plugins_root, &out_dir)
}

fn generate_manifest(crates_dir: &Path, out_dir: &str) -> Result<(), String> {
    // 目录内任何变化（新增/改名/删除/放 disabled 文件）都触发重扫。
    println!("cargo:rerun-if-changed={}", crates_dir.display());

    let mut plugins: Vec<String> = Vec::new(); // crate 名（rust 标识符形态，如 sl_plugin_storage）
    if crates_dir.is_dir() {
        let mut entries: Vec<_> = fs::read_dir(crates_dir)
            .map_err(|e| format!("读取插件目录 {} 失败：{e}", crates_dir.display()))?
            .collect::<Result<_, _>>()
            .map_err(|e| format!("读取插件目录 {} 失败：{e}", crates_dir.display()))?;
        entries.sort_by_key(|e| e.file_name());
        for entry in entries {
            let path = entry.path();
            if !path.is_dir() {
                continue;
            }
            let dir_name = entry.file_name().to_string_lossy().into_owned();
            if !dir_name.starts_with("plugin-") {
                continue;
            }
            // 禁用：整目录跳过（WIP 半成品可安全放这里）。
            if path.join("disabled").is_file() {
                continue;
            }
            let manifest = path.join("Cargo.toml");
            if !manifest.is_file() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", manifest.display());
            let crate_name = plugin_crate_name(&dir_name, &path, &manifest)?;
            plugins.push(crate_name);
        }
    }

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs（crates/plugin-* 自动发现，勿手改；规则见 docs/kernel-dev.md §4.4）\n",
    );
    code.push_str("use so_lite_agent::registry::KernelDescriptor;\n");
    code.push('\n');
    code.push_str(
        "/// 编译期内置内核插件清单（ADR-0036：构建期自动发现；Linus 模式仅维护者添加）。\n",
    );
    code.push_str("pub fn builtin_kernel_plugins() -> Vec<KernelDescriptor> {\n");
    code.push_str("    vec![\n");
    for name in &plugins {
        code.push_str(&format!("        {name}::descriptor(),\n"));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");
    fs::write(Path::new(out_dir).join("builtin_kernel_plugins.rs"), code)
        .map_err(|e| format!("写生成清单失败：{e}"))
}

/// 校验插件目录约定并返回插件 crate 名（rust 标识符形态）。
/// 约定：目录 `plugin-<name>` 内 Cargo.toml 的 `[package] name` 必须为 `sl-plugin-<name>`。
fn plugin_crate_name(dir_name: &str, dir: &Path, manifest: &Path) -> Result<String, String> {
    let name = dir_name.strip_prefix("plugin-").expect("已按前缀过滤");
    validate_dir_name(name, dir)?;

    let package_name = read_package_name(manifest)?;
    let expected = format!("sl-plugin-{name}");
    if package_name != expected {
        return Err(format!(
            "插件目录 {} 的包名应为 `{expected}`（目录 `plugin-{name}` 约定），实际是 `{package_name}`",
            dir.display()
        ));
    }
    Ok(package_name.replace('-', "_"))
}

/// 从 Cargo.toml 提取 `[package] name`（只支持字面量字符串，最小 TOML 解析）。
fn read_package_name(manifest: &Path) -> Result<String, String> {
    let text = fs::read_to_string(manifest)
        .map_err(|e| format!("读取 {} 失败：{e}", manifest.display()))?;
    let mut in_package = false;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if line.starts_with('[') {
            in_package = line == "[package]";
            continue;
        }
        if !in_package {
            continue;
        }
        let Some(rest) = line.strip_prefix("name") else {
            continue;
        };
        let Some(rest) = rest.trim_start().strip_prefix('=') else {
            continue;
        };
        let value = rest.trim().trim_matches('"').trim_matches('\'');
        if value.is_empty() || value.contains([' ', '\t', '#']) {
            return Err(format!(
                "{} 的 `name` 不是字面量字符串，无法自动发现：`{line}`",
                manifest.display()
            ));
        }
        return Ok(value.to_string());
    }
    Err(format!(
        "{} 缺少 `[package] name`，无法自动发现插件（约定 `sl-plugin-<name>`）",
        manifest.display()
    ))
}

fn validate_dir_name(name: &str, dir: &Path) -> Result<(), String> {
    let mut bytes = name.bytes();
    let valid = match bytes.next() {
        Some(b) if b.is_ascii_lowercase() => {
            bytes.all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        }
        _ => false,
    };
    if !valid {
        return Err(format!(
            "插件目录名 `plugin-{name}` 不合法：<name> 须为小写蛇形（^[a-z][a-z0-9_]*$）：{}",
            dir.display()
        ));
    }
    Ok(())
}
